checks:
    python:
        code_rating: true
        duplicate_code: true

filter:
    excluded_paths:
        - tests*
        - examples/*
        - doc/*
        - school_api/client/api/utils/schedule_parse.py